import type { IProjects, ISkillDatas } from './staticInterface';

export const projects: Array<IProjects> = [
	{
		name: 'Attendance & Payroll SaaS',
		link: 'attendance-saas',
		image: '/web-absen.png',
		type: 'SaaS Platform',
		tools: ['Next.js', 'Golang', 'PostgreSQL', 'Redis', 'Docker', 'Tailwind CSS'],
		skillKeys: ['react', 'go-lang', 'pgsql', 'tailwind-css', 'vercell'],
		description: 'project_content.attendance-saas.description',
		images: ['/web-absen.png'],
		url: 'https://landing-page-attendance.mahardikakdenie.my.id/',
		role: 'Fullstack Developer',
		year: '2024',
		features: [
			'project_content.attendance-saas.features.0',
			'project_content.attendance-saas.features.1',
			'project_content.attendance-saas.features.2',
			'project_content.attendance-saas.features.3'
		],
		challenges: 'project_content.attendance-saas.challenges',
		documentationLink: '/documentation/go-attendance-api'
	},
	{
		name: 'Monis Workspace - 3D Visual Product Configurator',
		link: 'monis-workspace',
		image: '/preview-studio.png',
		type: '3D Visual Products',
		tools: ['React', 'Three.js', 'React Three Fiber', 'Tailwind CSS', 'TypeScript'],
		skillKeys: ['react', 'tailwind-css', 'typescript'],
		description: 'project_content.monis-workspace.description',
		images: ['/preview-studio.png'],
		url: 'https://monis-studio.mahardikakdenie.my.id/',
		role: 'Frontend Engineer & 3D Developer',
		year: '2024',
		features: [
			'project_content.monis-workspace.features.0',
			'project_content.monis-workspace.features.1',
			'project_content.monis-workspace.features.2',
			'project_content.monis-workspace.features.3'
		],
		challenges: 'project_content.monis-workspace.challenges'
	},
	{
		name: 'Drag & Drop Web Builder',
		link: 'web-builder',
		image: '/preview-webbuilder.png',
		type: 'Web App',
		tools: ['React', 'TypeScript', 'Vite', 'Zustand', 'TailwindCss'],
		skillKeys: ['react', 'typescript', 'tailwind-css'],
		description: 'project_content.web-builder.description',
		images: ['/preview-webbuilder.png'],
		url: 'https://web-builder.mahardikakdenie.my.id/',
		role: 'Frontend Engineer',
		year: '2024',
		features: [
			'project_content.web-builder.features.0',
			'project_content.web-builder.features.1',
			'project_content.web-builder.features.2',
			'project_content.web-builder.features.3'
		],
		challenges: 'project_content.web-builder.challenges'
	},
	{
		name: 'Point Of Sales (Laukita Theme)',
		link: 'laukita-theme',
		image: '/laukita.png',
		type: 'Web App',
		tools: ['Vue3', 'Nuxt3', 'SEO', 'Pinia', 'TailwindCss', 'MockAPI'],
		skillKeys: ['vue', 'tailwind-css'],
		description: 'project_content.laukita-theme.description',
		images: ['/laukita.png', '/dashboard-laukita.png'],
		url: 'https://laukita.mahardikakdenie.my.id',
        role: 'Lead Frontend Engineer',
        year: '2024',
        features: [
            'project_content.laukita-theme.features.0',
            'project_content.laukita-theme.features.1',
            'project_content.laukita-theme.features.2',
            'project_content.laukita-theme.features.3',
            'project_content.laukita-theme.features.4'
        ],
        challenges: 'project_content.laukita-theme.challenges'
	},
	{
		name: 'Point Of Sales (Dreams Theme)',
		link: 'dreams-theme',
		image: 'https://jam.dev/cdn-cgi/image/width=1600,quality=100,dpr=1/https://cdn-jam-screenshots.jam.dev/a58ab27b92b27a46793582dd84a3484f/screenshot/99ea1a40-aa39-448b-b995-40fbba8bf136.png',
		type: 'Web App',
		tools: ['Vue3', 'Nuxt3', 'SEO', 'Pinia', 'TailwindCss', 'MockAPI'],
		skillKeys: ['vue', 'tailwind-css'],
		description: 'project_content.dreams-theme.description',
		images: ['https://jam.dev/cdn-cgi/image/width=1600,quality=100,dpr=1/https://cdn-jam-screenshots.jam.dev/a58ab27b92b27a46793582dd84a3484f/screenshot/99ea1a40-aa39-448b-b995-40fbba8bf136.png'],
		badge: 'Work In Progress [WIP]',
		url: "https://oddo-themes.mahardikakdenie.my.id/",
        role: 'UI/UX Developer',
        year: '2024',
        features: [
            'project_content.dreams-theme.features.0',
            'project_content.dreams-theme.features.1',
            'project_content.dreams-theme.features.2',
            'project_content.dreams-theme.features.3'
        ],
        challenges: 'project_content.dreams-theme.challenges'
	},
	{
		name: 'Template - Dashboard Theme',
		link: 'dashboard-admin-theme',
		image: 'https://jam.dev/cdn-cgi/image/width=1600,quality=100,dpr=1/https://cdn-jam-screenshots.jam.dev/890f14769162dacdb44537794706b300/screenshot/7a4c494b-0f51-4139-933f-3b57adec20fc.png',
		type: 'Web App',
		tools: ['Vue3', 'Nuxt3', 'SEO', 'Pinia', 'TailwindCss', 'MockAPI'],
		skillKeys: ['vue', 'tailwind-css'],
		description: 'project_content.dashboard-admin-theme.description',
		images: ['https://jam.dev/cdn-cgi/image/width=1600,quality=100,dpr=1/https://cdn-jam-screenshots.jam.dev/890f14769162dacdb44537794706b300/screenshot/7a4c494b-0f51-4139-933f-3b57adec20fc.png'],
		badge: 'Work In Progress [WIP]',
		url: "https://dashboard.ensiklotari.id/",
        role: 'Fullstack Developer',
        year: '2023',
        features: [
            'project_content.dashboard-admin-theme.features.0',
            'project_content.dashboard-admin-theme.features.1',
            'project_content.dashboard-admin-theme.features.2',
            'project_content.dashboard-admin-theme.features.3'
        ],
        challenges: 'project_content.dashboard-admin-theme.challenges'
	},
	{
		name: 'Customer Portal App',
		link: 'customer-portal-app',
		image: '/customer-portal-app.png',
		type: 'Mobile App',
		tools: [
			'Flutter',
			'Bloc Cubit',
			'Material UI',
			'Typescript',
			'Nestjs',
			'Microservice API',
		],
		skillKeys: ['typescript', 'nodejs'],
		description: 'project_content.customer-portal-app.description',
		images: ['/customer-portal-app.png'],
        role: 'Mobile Developer',
        year: '2023',
        features: [
            'project_content.customer-portal-app.features.0',
            'project_content.customer-portal-app.features.1',
            'project_content.customer-portal-app.features.2',
            'project_content.customer-portal-app.features.3'
        ],
        challenges: 'project_content.customer-portal-app.challenges'
	},
	{
		name: 'API Service - IMGDBB',
		link: 'api-service-imgbb',
		image: '/imgbb-api.png',
		type: 'SERVICE API',
		tools: ['IMGBB API SERVICE', 'NodeExpress', 'Typescript'],
		skillKeys: ['nodejs', 'expressjs', 'typescript'],
		url: 'https://github.com/mahardikakdenie/cloud-api-imgbb',
		description: 'project_content.api-service-imgbb.description',
		images: ['/imgbb-api.png'],
        role: 'Backend Engineer',
        year: '2024',
        features: [
            'project_content.api-service-imgbb.features.0',
            'project_content.api-service-imgbb.features.1',
            'project_content.api-service-imgbb.features.2',
            'project_content.api-service-imgbb.features.3'
        ],
        challenges: 'project_content.api-service-imgbb.challenges'
	},
	{
		name: 'Floucloud Id',
		link: 'floucloud',
		image: '/floucloud.jpg',
		type: 'Web App',
		tools: [
			'Vue3',
			'Nuxt3',
			'SEO',
			'Pinia',
			'TailwindCss',
			'.Net Core',
			'PostgreeSQL',
		],
		skillKeys: ['vue', 'tailwind-css', 'pgsql'],
		description: 'project_content.floucloud.description',
		images: ['/floucloud.jpg'],
        role: 'Lead Developer',
        year: '2023',
        features: [
            'project_content.floucloud.features.0',
            'project_content.floucloud.features.1',
            'project_content.floucloud.features.2',
            'project_content.floucloud.features.3'
        ],
        challenges: 'project_content.floucloud.challenges'
	},
	{
		name: 'Ticketing Portal Automation',
		link: 'ticketing-portal-automation',
		image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1000&auto=format&fit=crop',
		type: 'Automation',
		tools: ['GitHub Apps', 'Webhooks', 'Node.js', 'Typescript'],
		skillKeys: ['nodejs', 'typescript'],
		description: 'project_content.ticketing-portal-automation.description',
		images: ['https://images.unsplash.com/photo-1516321318423-f06f85e504b3?q=80&w=1000&auto=format&fit=crop'],
        role: 'DevOps & Automation Engineer',
        year: '2024',
        features: [
            'project_content.ticketing-portal-automation.features.0',
            'project_content.ticketing-portal-automation.features.1',
            'project_content.ticketing-portal-automation.features.2',
            'project_content.ticketing-portal-automation.features.3'
        ],
        challenges: 'project_content.ticketing-portal-automation.challenges',
        documentationLink: '/documentation/automating-ticketing-with-github-apps'
	},
	{
		name: 'VueButton – Build with Vue 3',
		link: 'vue-button',
		image: '/lib-btn.png',
		type: 'Package Vue UI',
		description: 'project_content.vue-button.description',
		tools: ['Vue3', 'npm', 'Vite'],
		skillKeys: ['vue'],
		images: ['/lib-btn.png'],
		badge: 'Personal Package',
		url: 'https://www.npmjs.com/package/mahardikakdenie-vue-button',
        role: 'Open Source Creator',
        year: '2024',
        features: [
            'project_content.vue-button.features.0',
            'project_content.vue-button.features.1',
            'project_content.vue-button.features.2',
            'project_content.vue-button.features.3'
        ],
        challenges: 'project_content.vue-button.challenges',
        documentationLink: '/documentation/button-component'
	},
	{
		name: 'Zoom OAuth Integration (PoC)',
		link: 'zoom-oauth-integration',
		image: 'https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?q=80&w=1000&auto=format&fit=crop',
		type: 'Integration',
		tools: ['Vue2', 'OAuth 2.0', 'Ngrok', 'Axios', 'Node.js'],
		skillKeys: ['vue', 'nodejs'],
		description: 'project_content.zoom-oauth-integration.description',
		images: [
            'https://images.unsplash.com/photo-1588196749597-9ff075ee6b5b?q=80&w=1000&auto=format&fit=crop',
            'https://images.unsplash.com/photo-1611162617213-7d7a39e9b1d7?q=80&w=1000&auto=format&fit=crop'
        ],
		url: 'https://github.com/mahardikakdenie/VUEJS_NGROK_ZOOM_Outh',
        role: 'Security & Integration Engineer',
        year: '2024',
        features: [
            'project_content.zoom-oauth-integration.features.0',
            'project_content.zoom-oauth-integration.features.1',
            'project_content.zoom-oauth-integration.features.2',
            'project_content.zoom-oauth-integration.features.3',
            'project_content.zoom-oauth-integration.features.4'
        ],
        challenges: 'project_content.zoom-oauth-integration.challenges',
        documentationLink: '/documentation/zoom-oauth-integration'
	},
    {
		name: 'Ensiklotari',
		link: 'ensiklotari',
		image: '/ensiklotari.png',
		description: 'project_content.ensiklotari.description',
		skillKeys: ['vue', 'laravel', 'mysql', 'tailwind-css'],
		images: ['/ensiklotari.png', '/bujanggamanik.png'],
		type: 'Web App',
		tools: ['Vue3', 'Laravel', 'Mysql', 'Pinia', 'TailwindCss'],
        role: 'Fullstack Developer',
        year: '2022',
        features: [
            'project_content.ensiklotari.features.0',
            'project_content.ensiklotari.features.1',
            'project_content.ensiklotari.features.2',
            'project_content.ensiklotari.features.3'
        ],
        challenges: 'project_content.ensiklotari.challenges'
	},
    {
		name: 'CMS HAYS GALLERY',
		link: 'cms-hays-gallery',
		image: '/cms-hays-login.png',
		description: 'project_content.cms-hays-gallery.description',
		skillKeys: ['react', 'tailwind-css'],
		images: ['/cms-hays-login.png'],
		type: 'Web App',
		tools: ['React', 'Next.js', 'Tailwind CSS'],
        role: 'Frontend Developer',
        year: '2023',
        features: [
            'project_content.cms-hays-gallery.features.0',
            'project_content.cms-hays-gallery.features.1'
        ],
        challenges: 'project_content.cms-hays-gallery.challenges'
	},
    {
		name: 'Maida Clinic Landing Page',
		link: 'maida-clinic',
		image: '/maida-clinik-1.png',
		description: 'project_content.maida-clinic.description',
		skillKeys: ['vue'],
		images: ['/maida-clinik-1.png'],
		type: 'Landing Page',
		tools: ['Nuxt 3', 'Vue 3', 'SEO'],
        role: 'Frontend Developer',
        year: '2023',
        features: [
            'project_content.maida-clinic.features.0',
            'project_content.maida-clinic.features.1'
        ],
        challenges: 'project_content.maida-clinic.challenges'
	},
    {
		name: 'PM TRICK – LMS Web App',
		link: 'pm-tricks-lms',
		image: '/pm-trick.png',
		description: 'project_content.pm-tricks-lms.description',
		skillKeys: ['vue', 'tailwind-css', 'typescript'],
		images: ['/pm-trick.png'],
		type: 'Web App',
		tools: ['Vue 3', 'Tailwind', 'Typescript'],
        role: 'Fullstack Developer',
        year: '2023',
        features: [
            'project_content.pm-tricks-lms.features.0',
            'project_content.pm-tricks-lms.features.1'
        ],
        challenges: 'project_content.pm-tricks-lms.challenges'
	},
    {
		name: 'Store Vue - Ecommerce',
		link: 'store-vue-catalog',
		image: '/store-slicing.png',
		description: 'project_content.store-vue-catalog.description',
		skillKeys: ['vue', 'tailwind-css'],
		images: ['/store-slicing.png'],
		type: 'Web App',
		tools: ['Nuxt.js', 'Vue', 'Tailwind CSS'],
        role: 'Frontend Developer',
        year: '2023',
        features: [
            'project_content.store-vue-catalog.features.0',
            'project_content.store-vue-catalog.features.1'
        ],
        challenges: 'project_content.store-vue-catalog.challenges'
	},
    {
		name: 'Dikti Application Profile',
		link: 'dikti-company',
		image: '/dikti.png',
		description: 'project_content.dikti-company.description',
		skillKeys: ['css3'],
		images: ['/dikti.png'],
		type: 'Web App',
		tools: ['Web', 'CSS'],
        role: 'Frontend Developer',
        year: '2022',
        features: [
            'project_content.dikti-company.features.0'
        ],
        challenges: 'project_content.dikti-company.challenges'
	},
    {
		name: 'Uniqlo Theme Slicing',
		link: 'uniqlo-slicing',
		image: '/uniqlo-theme.png',
		description: 'project_content.uniqlo-slicing.description',
		skillKeys: ['html5', 'css3'],
		images: ['/uniqlo-theme.png'],
		type: 'Slicing UI',
		tools: ['HTML', 'CSS', 'Slicing'],
        role: 'UI Developer',
        year: '2022',
        features: [
            'project_content.uniqlo-slicing.features.0'
        ],
        challenges: 'project_content.uniqlo-slicing.challenges'
	},
    {
		name: 'Next Movie App',
		link: 'next-movie-app',
		image: '/next-movie.png',
		description: 'project_content.next-movie-app.description',
		skillKeys: ['react'],
		images: ['/next-movie.png'],
		type: 'Web App',
		tools: ['Next.js', 'React', 'TMDB API'],
        role: 'Frontend Developer',
        year: '2022',
        features: [
            'project_content.next-movie-app.features.0',
            'project_content.next-movie-app.features.1'
        ],
        challenges: 'project_content.next-movie-app.challenges'
	},
    {
		name: 'BujanggaManik Appointment',
		link: 'bujangga-manik-app',
		image: '/bujanggamanik.png',
		description: 'project_content.bujangga-manik-app.description',
		skillKeys: ['php'],
		images: ['/bujanggamanik.png'],
		type: 'Web App',
		tools: ['Web', 'PHP'],
        role: 'Fullstack Developer',
        year: '2022',
        features: [
            'project_content.bujangga-manik-app.features.0',
            'project_content.bujangga-manik-app.features.1'
        ],
        challenges: 'project_content.bujangga-manik-app.challenges'
	},
    {
		name: 'Smile Learning Center LMS',
		link: 'slc-lms',
		image: '/lms.png',
		description: 'project_content.slc-lms.description',
		skillKeys: ['php', 'mysql'],
		images: ['/lms.png'],
		type: 'Web App',
		tools: ['Web', 'PHP', 'MySQL'],
        role: 'Fullstack Developer',
        year: '2022',
        features: [
            'project_content.slc-lms.features.0'
        ],
        challenges: 'project_content.slc-lms.challenges'
	},
    {
		name: 'Tic Tac Toe - Interactive',
		link: 'tic-tac-toe',
		image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Tic_tac_toe.svg/400px-Tic_tac_toe.svg.png',
		description: 'project_content.tic-tac-toe.description',
		skillKeys: ['react', 'javascript'],
		images: ['https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Tic_tac_toe.svg/400px-Tic_tac_toe.svg.png'],
		type: 'Game',
		tools: ['React', 'JavaScript'],
        role: 'Frontend Developer',
        year: '2022',
        features: [
            'project_content.tic-tac-toe.features.0'
        ],
        challenges: 'project_content.tic-tac-toe.challenges'
	},
    {
		name: 'RESTful Book Library API',
		link: 'book-library-api',
		image: 'https://images.unsplash.com/photo-1507842217343-583bb7270b66?q=80&w=1000&auto=format&fit=crop',
		description: 'project_content.book-library-api.description',
		skillKeys: ['go-lang', 'pgsql'],
		images: ['https://images.unsplash.com/photo-1507842217343-583bb7270b66?q=80&w=1000&auto=format&fit=crop'],
		type: 'Backend API',
		tools: ['Golang', 'PostgreSQL'],
        role: 'Backend Engineer',
        year: '2023',
        features: [
            'project_content.book-library-api.features.0'
        ],
        challenges: 'project_content.book-library-api.challenges'
	},
];

export const skillDatas: Array<ISkillDatas> = [
	{
		title: 'ReactJS',
		key: 'react',
		current_thumb: '/react.png',
		thumb: '/react.png',
		thumb_active: '/react.png',
		image: '/react.png',
		description: 'skills_content.react',
		experienceSkill: 'Expert',
		yearExperience: '5+',
	},
	{
		title: 'Vuejs',
		key: 'vue',
		thumb: 'vue.png',
		image: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/vuejs/vuejs-original.svg',
		description: 'skills_content.vue',
		experienceSkill: 'Expert',
		yearExperience: '5+',
	},
	{
		title: 'Nodejs',
		key: 'nodejs',
		thumb: 'node.png',
		image: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/nodejs/nodejs-original.svg',
		description: 'skills_content.node',
		experienceSkill: 'Expert',
		yearExperience: '5+',
	},
	{
		title: 'Expressjs',
		key: 'expressjs',
		thumb: 'express.png',
		image: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/express/express-original.svg',
		description: 'skills_content.express',
		experienceSkill: 'Expert',
		yearExperience: '5+',
	},
	{
		title: 'Golang',
		key: 'go-lang',
		thumb: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/go/go-original.svg',
		image: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/go/go-original.svg',
		description: 'skills_content.golang',
		experienceSkill: 'Expert',
		yearExperience: '5+',
	},
	{
		title: 'HTML5',
		key: 'html5',
		thumb: 'html.png',
		image: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/html5/html5-original.svg',
		description: 'skills_content.html5',
		experienceSkill: 'Expert',
		yearExperience: '5+',
	},
	{
		title: 'Tailwind CSS',
		key: 'tailwind-css',
		thumb: 'tailwindcss.png',
		image: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/tailwindcss/tailwindcss-original.svg',
		description: 'skills_content.tailwind',
		experienceSkill: 'Expert',
		yearExperience: '5+',
	},
	{
		title: 'Bootstrap',
		key: 'bootstrap',
		thumb: 'boostrap.png',
		image: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/bootstrap/bootstrap-original.svg',
		description: 'skills_content.bootstrap',
		experienceSkill: 'Expert',
		yearExperience: '5+',
	},
	{
		title: 'SASS',
		key: 'sass',
		thumb: 'saas.png',
		image: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/sass/sass-original.svg',
		description: 'skills_content.sass',
		experienceSkill: 'Expert',
		yearExperience: '5+',
	},
	{
		title: 'CSS3',
		key: 'css3',
		thumb: 'css3.png',
		image: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/css3/css3-original.svg',
		description: 'skills_content.css3',
		experienceSkill: 'Expert',
		yearExperience: '5+',
	},
	{
		title: 'JavaScript',
		key: 'javascript',
		thumb: 'javascript.png',
		image: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/javascript/javascript-original.svg',
		description: 'skills_content.js',
		experienceSkill: 'Expert',
		yearExperience: '6+',
	},
	{
		title: 'TypeScript',
		key: 'typescript',
		thumb: 'typescript.png',
		image: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/typescript/typescript-original.svg',
		description: 'skills_content.ts',
		experienceSkill: 'Expert',
		yearExperience: '5+',
	},
	{
		title: 'PHP',
		key: 'php',
		thumb: 'php.png',
		image: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/php/php-original.svg',
		description: 'skills_content.php',
		experienceSkill: 'Expert',
		yearExperience: '5+',
	},
	{
		title: 'CodeIgniter',
		key: 'codeIgniter',
		thumb: 'ci.png',
		image: 'https://cdn.iconscout.com/icon/free/png-256/free-codeigniter-3-1175229.png',
		description: 'skills_content.ci',
		experienceSkill: 'Expert',
		yearExperience: '5+',
	},
	{
		title: 'Laravel',
		key: 'laravel',
		thumb: 'laravel.png',
		image: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/laravel/laravel-original.svg',
		description: 'skills_content.laravel',
		experienceSkill: 'Expert',
		yearExperience: '5+',
	},
	{
		title: 'Mysql',
		key: 'mysql',
		thumb: 'mysql.png',
		image: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/mysql/mysql-original.svg',
		description: 'skills_content.mysql',
		experienceSkill: 'Expert',
		yearExperience: '5+',
	},
	{
		title: 'Vercell',
		key: 'vercell',
		thumb: 'https://assets.vercel.app/image/upload/v1588805858/repositories/vercel/logo.png',
		image: 'https://assets.vercel.app/image/upload/v1588805858/repositories/vercel/logo.png',
		description: 'skills_content.vercel',
		experienceSkill: 'Expert',
		yearExperience: '5+',
	},
	{
		title: 'PostgreSql',
		key: 'pgsql',
		thumb: 'pgsql.png',
		image: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/postgresql/postgresql-original.svg',
		description: 'skills_content.pgsql',
		experienceSkill: 'Expert',
		yearExperience: '5+',
	},
	{
		title: 'MongooDB',
		key: 'mongoodb',
		thumb: 'mongoo.png',
		image: 'https://raw.githubusercontent.com/devicons/devicon/master/icons/mongodb/mongodb-original.svg',
		description: 'skills_content.mongodb',
		experienceSkill: 'Expert',
		yearExperience: '5+',
	},
];
